# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f84ad934a3d7dd4c5112dcfa32b2ca91cdbf5dbed33558a1f6cc7915aea39e334ef4b8b544ddbe4d4d9eb30a0c11fee4525c5859ba0704f49623308b05e0241e

test:
  secret_key_base: 97b38bb427a6768d108c3ea31e57cb9f3e7240552dc3855f6997ccf8a860610eedd0f07e3d9ae31578864078aab2c9fc1da6715dd6b4d5d654778a3859cfe252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
